# Generated by Django 5.1.1 on 2024-09-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_task_descriptions_en_task_descriptions_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='descriptions_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='title_tr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
